### PR TITLE
Changes to analytics util,  to create formatting for stan outputs

### PR DESCRIPTION
**Pull request by tamisalex**

### CODE REVIEW

**Comment by jpfairbanks** [comment]
This change would mean that every time an opal produced a summary.txt it would get the special treatment. I am concerned about the number of corner cases that this will generate. 

Can the problem be solved by making this printing a method on the opal?

**Comment by sirpoovey** [comment]
How about check to see if outputData is a list or a string, if it's a string, just write it.  If it's a list, then join the elements and then write it.

**Comment by tamisalex** [comment]
I agree James. Its been a while since I have actually done software development so my changes were quick and dirty.

I will override the write_output function in the Stan Opal

**Comment by tamisalex** [comment]
Closing, moving functionality to opal-analytics-stan

**Pull request closed without merging**
